# Custom exceptions

:::functions.custom_exceptions